# @domain=http://localhost:3000
@domain=https://react-do-server-production.up.railway.app
# @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM0ODEwOTYxOTUzNjA0MGY4MWQwYmMiLCJ1c2VybmFtZSI6ImtydXNobiIsImlhdCI6MTcxNDcxNjk0MX0.7oVRZME8AgZOLIsiX8stoHDNTXEYMjXZ17rl6bzXNK4
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjM0ODU0MzY1OGZhODQzMWFmNGM3N2YiLCJ1c2VybmFtZSI6ImtydXNobiIsImlhdCI6MTcxNDcxODAyOX0.ZbwhdE2V4XiRklfNlBmzVlvI_8rLQwJhWnJfxmMQ0IM
###
POST {{domain}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
  "username": "krushn",
  "password": "krushn"
}

###
POST {{domain}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
  "username": "krushn",
  "password": "krushn"
}

###
POST {{domain}}/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Learn Node.js"
}

###
POST {{domain}}/todos-insecure HTTP/1.1
Content-Type: application/json

{
  "text": "Learn Node.js Insecure Krushn"
}

###
POST {{domain}}/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  
}

###
GET {{domain}}/todos HTTP/1.1
Content-Type: application/json

###
GET {{domain}}/todos/66347fd1cd41a85690f2edd5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
PUT {{domain}}/todos/66348141619536040f81d0c1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Learn Node.js Update",
  "isDone": true 
}

###
DELETE {{domain}}/todos/66347fd1cd41a85690f2edd5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Admin

DELETE {{domain}}/admin/todos HTTP/1.1

###

DELETE {{domain}}/admin/users HTTP/1.1

###